(require 'org-pretty-tags)

(defun tags-beautify ()
  "Beautify Tags"
  (setq org-pretty-tags-surrogate-strings nil)
  (setq org-pretty-tags-surrogate-strings
        (append org-pretty-tags-surrogate-strings
                `(("Idea"       . ,(all-the-icons-faicon  "lightbulb-o"  ))
                  ("Deprecated" . ,(all-the-icons-faicon  "strikethrough"))
                  ("Block"      . ,(all-the-icons-material "block"       ))
                  ("Lock"       . ,(all-the-icons-faicon   "lock"        ))
                  ("Unlock"     . ,(all-the-icons-faicon   "unlock"      ))
                  ("Key"        . ,(all-the-icons-faicon   "key"         ))
                  ("Encrypted"  . ,(all-the-icons-faicon   "lock"        ))
                  ("Decrypted"  . ,(all-the-icons-faicon   "unlock"      ))
                  ("Certificate". ,(all-the-icons-faicon   "certificate" ))
                  ("Fingerprint". ,(all-the-icons-material "fingerprint" ))
                  ("Private"    . ,(all-the-icons-material "fingerprint" ))
                  ("Privacy"    . ,(all-the-icons-material "fingerprint" ))
                  ("Email"      . ,(all-the-icons-faicon   "envelope"    ))
                  ("Read"       . ,(all-the-icons-octicon  "book"        ))
                  ("Article"    . ,(all-the-icons-octicon  "file-text"   ))
                  ("Web"        . ,(all-the-icons-faicon   "globe"       ))
                  ("Info"       . ,(all-the-icons-faicon   "info-circle" ))
                  ("Issue"      . ,(all-the-icons-faicon   "bug"         ))
                  ("Someday"    . ,(all-the-icons-faicon   "calendar-o"  ))
                  ("Music"      . ,(all-the-icons-faicon   "music"       ))
                  ("Idea"       . ,(all-the-icons-octicon  "light-bulb"  ))
                  ("DarkOs"     . ,(all-the-icons-fileicon "arch-linux"  ))
                  ("Emacs"      . ,(all-the-icons-fileicon "emacs"       ))
                  ("Suggested"  . ,(all-the-icons-faicon   "star"        ))
                  ("Favorite"   . ,(all-the-icons-faicon   "star-o"      ))
                  ("Recommended". ,(all-the-icons-faicon   "thumbs-up"   ))
                  ("notify"     . ,(all-the-icons-faicon   "bell-o"      ))
                  ("task"       . ,(all-the-icons-faicon   "check"       ))
                  ("event_busy" . ,(all-the-icons-material "event_busy"  ))
                  ("check"      . ,(all-the-icons-faicon   "check"       ))
                  ("alert"      . ,(all-the-icons-material "add_alert"   ))
                  ("important"  . ,(all-the-icons-material "priority_high"))
                  ("repeat"     . ,(all-the-icons-faicon   "repeat"      ))
                  ("delete"     . ,(all-the-icons-material "delete"      ))
                  ("cancel"     . ,(all-the-icons-material "cancel"      ))
                  ("inprogress" . ,(all-the-icons-faicon   "spinner"     ))
                  ("forum"      . ,(all-the-icons-material "forum"       ))
                  ("talk"       . ,(all-the-icons-faicon   "comments-o"  ))
                  ("call"       . ,(all-the-icons-material "call"        ))
                  ("voice_chat" . ,(all-the-icons-material "voice_chat"  ))
                  ("contact"    . ,(all-the-icons-material "account_box" ))
                  ("person"     . ,(all-the-icons-material "person"      ))
                  ("person_pin" . ,(all-the-icons-material "person_pin"  ))
                  ("user"       . ,(all-the-icons-faicon   "user"        ))
                  ("users"      . ,(all-the-icons-faicon   "users"       ))
                  ("group"      . ,(all-the-icons-material "group"       ))
                  ("gift"       . ,(all-the-icons-faicon   "gift"        ))
                  ("weekend"    . ,(all-the-icons-material "weekend"     ))
                  ("party"      . ,(all-the-icons-faicon   "beer"        ))
                  ("money"      . ,(all-the-icons-faicon   "money"       ))
                  ("build"      . ,(all-the-icons-material "build"       ))
                  ("sleep"      . ,(all-the-icons-faicon   "bed"         ))
                  ("payment"    . ,(all-the-icons-faicon   "credit-card" ))
                  ("movie"      . ,(all-the-icons-material "movie"       ))
                  ("watch"      . ,(all-the-icons-faicon   "eye"         ))
                  ("book"       . ,(all-the-icons-octicon  "book"        ))
                  ("walk"       . ,(all-the-icons-material "directions_walk"))
                  ("run"        . ,(all-the-icons-material "directions_run"))
                  ("write"      . ,(all-the-icons-faicon   "pencil"      ))
                  ("code"       . ,(all-the-icons-material "code"        ))
                  ("heart"      . ,(all-the-icons-faicon   "heart-o"     )))))
  (org-pretty-tags-global-mode 1)
  (with-eval-after-load 'org
    (setq org-tag-alist
          (append org-tag-alist
                  (append
                   '((:startgrouptag)) '(("icons"))
                   '((:grouptags)) (mapcar 'list (mapcar 'car org-pretty-tags-surrogate-strings))
                   '((:endgrouptag)))))))
(defun tags-beautify-stop ()
  (setq org-pretty-tags-surrogate-strings nil)
  (org-pretty-tags-global-mode -1))

;; (use-package! org-pretty-tags
;;   :init (org-pretty-tags-global-mode 1)
;;   :config
;;   ;; (setq org-pretty-tags-surrogate-strings
;;   ;;       `(("uni"        . ,(all-the-icons-faicon   "graduation-cap" :face 'all-the-icons-purple  :v-adjust 0.01))
;;   ;;         ("ucc"        . ,(all-the-icons-material "computer"       :face 'all-the-icons-silver  :v-adjust 0.01))
;;   ;;         ("assignment" . ,(all-the-icons-material "library_books"  :face 'all-the-icons-orange  :v-adjust 0.01))
;;   ;;         ("test"       . ,(all-the-icons-material "timer"          :face 'all-the-icons-red     :v-adjust 0.01))
;;   ;;         ("lecture"    . ,(all-the-icons-fileicon "keynote"        :face 'all-the-icons-orange  :v-adjust 0.01))
;;   ;;         ("email"      . ,(all-the-icons-faicon   "envelope"       :face 'all-the-icons-blue    :v-adjust 0.01))
;;   ;;         ("read"       . ,(all-the-icons-octicon  "book"           :face 'all-the-icons-lblue   :v-adjust 0.01))
;;   ;;         ("article"    . ,(all-the-icons-octicon  "file-text"      :face 'all-the-icons-yellow  :v-adjust 0.01))
;;   ;;         ("web"        . ,(all-the-icons-faicon   "globe"          :face 'all-the-icons-green   :v-adjust 0.01))
;;   ;;         ("info"       . ,(all-the-icons-faicon   "info-circle"    :face 'all-the-icons-blue    :v-adjust 0.01))
;;   ;;         ("issue"      . ,(all-the-icons-faicon   "bug"            :face 'all-the-icons-red     :v-adjust 0.01))
;;   ;;         ("someday"    . ,(all-the-icons-faicon   "calendar-o"     :face 'all-the-icons-cyan    :v-adjust 0.01))
;;   ;;         ("music"      . ,(all-the-icons-faicon   "music"          :face 'all-the-icons-cyan    :v-adjust 0.01))
;;   ;;         ("idea"       . ,(all-the-icons-octicon  "light-bulb"     :face 'all-the-icons-yellow  :v-adjust 0.01))
;;   ;;         ("DarkOs"     . ,(all-the-icons-fileicon "arch-linux"     :face 'all-the-icons-yellow  :v-adjust 0.01))
;;   ;;         ("emacs"      . ,(all-the-icons-fileicon "emacs"          :face 'all-the-icons-lpurple :v-adjust 0.01))))

;;   (setq org-pretty-tags-surrogate-strings
;;         (append org-pretty-tags-surrogate-strings
;;                 `(("Idea"       . ,(all-the-icons-faicon  "lightbulb-o"  ))
;;                   ("Deprecated" . ,(all-the-icons-faicon  "strikethrough"))
;;                   ("Block"      . ,(all-the-icons-material "block"       ))
;;                   ("Lock"       . ,(all-the-icons-faicon   "lock"        ))
;;                   ("Unlock"     . ,(all-the-icons-faicon   "unlock"      ))
;;                   ("Key"        . ,(all-the-icons-faicon   "key"         ))
;;                   ("Encrypted"  . ,(all-the-icons-faicon   "lock"        ))
;;                   ("Decrypted"  . ,(all-the-icons-faicon   "unlock"      ))
;;                   ("Certificate". ,(all-the-icons-faicon   "certificate" ))
;;                   ("Fingerprint". ,(all-the-icons-material "fingerprint" ))
;;                   ("Private"    . ,(all-the-icons-material "fingerprint" ))
;;                   ("Privacy"    . ,(all-the-icons-material "fingerprint" ))
;;                   ("Email"      . ,(all-the-icons-faicon   "envelope"    ))
;;                   ("Read"       . ,(all-the-icons-octicon  "book"        ))
;;                   ("Article"    . ,(all-the-icons-octicon  "file-text"   ))
;;                   ("Web"        . ,(all-the-icons-faicon   "globe"       ))
;;                   ("Info"       . ,(all-the-icons-faicon   "info-circle" ))
;;                   ("Issue"      . ,(all-the-icons-faicon   "bug"         ))
;;                   ("Someday"    . ,(all-the-icons-faicon   "calendar-o"  ))
;;                   ("Music"      . ,(all-the-icons-faicon   "music"       ))
;;                   ("Idea"       . ,(all-the-icons-octicon  "light-bulb"  ))
;;                   ("DarkOs"     . ,(all-the-icons-fileicon "arch-linux"  ))
;;                   ("Emacs"      . ,(all-the-icons-fileicon "emacs"       ))
;;                   ("Suggested"  . ,(all-the-icons-faicon   "star"        ))
;;                   ("Favorite"   . ,(all-the-icons-faicon   "star-o"      ))
;;                   ("Recommended". ,(all-the-icons-faicon   "thumbs-up"   ))
;;                   ("notify"     . ,(all-the-icons-faicon   "bell-o"      ))
;;                   ("task"       . ,(all-the-icons-faicon   "check"       ))
;;                   ("event_busy" . ,(all-the-icons-material "event_busy"  ))
;;                   ("check"      . ,(all-the-icons-faicon   "check"       ))
;;                   ("alert"      . ,(all-the-icons-material "add_alert"   ))
;;                   ("important"  . ,(all-the-icons-material "priority_high"))
;;                   ("repeat"     . ,(all-the-icons-faicon   "repeat"      ))
;;                   ("delete"     . ,(all-the-icons-material "delete"      ))
;;                   ("cancel"     . ,(all-the-icons-material "cancel"      ))
;;                   ("inprogress" . ,(all-the-icons-faicon   "spinner"     ))
;;                   ("forum"      . ,(all-the-icons-material "forum"       ))
;;                   ("talk"       . ,(all-the-icons-faicon   "comments-o"  ))
;;                   ("call"       . ,(all-the-icons-material "call"        ))
;;                   ("voice_chat" . ,(all-the-icons-material "voice_chat"  ))
;;                   ("contact"    . ,(all-the-icons-material "account_box" ))
;;                   ("person"     . ,(all-the-icons-material "person"      ))
;;                   ("person_pin" . ,(all-the-icons-material "person_pin"  ))
;;                   ("user"       . ,(all-the-icons-faicon   "user"        ))
;;                   ("users"      . ,(all-the-icons-faicon   "users"       ))
;;                   ("group"      . ,(all-the-icons-material "group"       ))
;;                   ("gift"       . ,(all-the-icons-faicon   "gift"        ))
;;                   ("weekend"    . ,(all-the-icons-material "weekend"     ))
;;                   ("party"      . ,(all-the-icons-faicon   "beer"        ))
;;                   ("money"      . ,(all-the-icons-faicon   "money"       ))
;;                   ("build"      . ,(all-the-icons-material "build"       ))
;;                   ("sleep"      . ,(all-the-icons-faicon   "bed"         ))
;;                   ("payment"    . ,(all-the-icons-faicon   "credit-card" ))
;;                   ("movie"      . ,(all-the-icons-material "movie"       ))
;;                   ("watch"      . ,(all-the-icons-faicon   "eye"         ))
;;                   ("book"       . ,(all-the-icons-octicon  "book"        ))
;;                   ("walk"       . ,(all-the-icons-material "directions_walk"))
;;                   ("run"        . ,(all-the-icons-material "directions_run"))
;;                   ("write"      . ,(all-the-icons-faicon   "pencil"      ))
;;                   ("code"       . ,(all-the-icons-material "code"        ))
;;                   ("heart"      . ,(all-the-icons-faicon   "heart-o"     )))))
;;   (with-eval-after-load 'org
;;     (setq org-tag-alist
;;           (append org-tag-alist
;;                   (append
;;                    '((:startgrouptag)) '(("icons"))
;;                    '((:grouptags)) (mapcar 'list (mapcar 'car org-pretty-tags-surrogate-strings))
;;                    '((:endgrouptag)))))))

;; (use-package! org-tag-beautify
;;   :after org-pretty-tags
;;   :init (org-tag-beautify-mode 1))
