#!/usr/bin/env bash


# Herbstluftwm Config
# This File Contains My Personal KeyBindings And Some stuff


hc() {
    herbstclient "$@"
}

hc emit_hook reload
xsetroot -solid '#313330'
picom &
$HOME/.config/herbstluftwm/start.sh
nm-applet &
nitrogen --restore &
numlockx on &
dunst -conf ~/.config/dunst/dunstrc &
xfce4-power-manager &
/usr/lib/polkit-kde-authentication-agent-1 &
/usr/bin/emacs --daemon &
xscreensaver -no-splash &
caffeine &
#~/.config/herbstluftwm/uminimize.sh &
#jgmenu --hide-on-startup --config-file=~/.config/jgmenu/jgmenurc --csv-file=~/.config/jgmenu/menu.csv
#xclickroot -r jgmenu_run

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4                            # Use the super key as the main modifier
myTerm=xterm                   # Set my preferred terminal
myEditor="emacsclient -c -a emacs"  # Set my preferred editor
myBrowser="/usr/local/bin/librewolf"
myMusic="/usr/bin/mocp"
myMMusic="ncmpcpp"
MMControl="mpc"
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn $myTerm
hc keybind $Mod-e spawn $myEditor
# Dmenu launcher
hc keybind $Mod-Shift-Return spawn dmenu_run -fn 'scientifica:size=11' -nb '#212D32' -nf '#bbc5ff' -sb '#E37673' -sf '#292d3e' -p 'Ybenel:'
hc keybind $Mod-Mod1-s spawn dmenu_run -c -bw 2 -l 10 -g 4 -p 'ybenel: ' -fn 'scientifica:size=11'

# My dmenu scripts (Alt+Ctrl+Key)
hc keybind Mod1-Control-e spawn ./.dmenu/dmenu-edit-configs.sh
hc keybind Mod1-Control-h spawn ./.dmenu/dmenu-sysmon.sh
hc keybind Mod1-Control-s spawn ./.dmenu/dmenu-scrot.sh
hc keybind Mod1-Control-p spawn passmenu
hc keybind $Mod-Control-s spawn rofi -combi-modi run,drun -show combi -modi combi -show-icons -icon-theme 'Adwaita' -display-combi 'ybenel: '

# My applications (Super+Alt+Key)
hc keybind $Mod-Mod1-n spawn librewolf
hc keybind $Mod-Mod1-l spawn $myTerm -e lynx --cfg=~/.lynx/lynx.cfg --lss=~/.lynx/lynx.lss -vikeys https://music.ybenel.cf
hc keybind $Mod-Mod1-e spawn $myTerm -e irssi
hc keybind $Mod-Mod1-f spawn $myTerm -e ~/.config/vifm/scripts/vifmrun
hc keybind $Mod-Mod1-c spawn $myTerm -e $myMusic
hc keybind $Mod-Mod1-z spawn $myTerm -e $myMMusic
hc keybind $Mod-Mod1-h spawn $myTerm -e htop

# My Secondary Applications
hc keybind $Mod-Control-Return spawn $myTerm
hc keybind $Mod-Control-x spawn discord
hc keybind $Mod-Control-p spawn qjackctl
hc keybind $Mod-Control-e spawn $myTerm -e torify irssi
hc keybind $Mod-b spawn $myBrowser " file:///home/ybenel/Downloads/StartPage/homepage.html"


# Controllers
hc keybind $Mod-Mod1-p spawn $myTerm -e $myMusic --play
hc keybind $Mod-Mod1-l spawn $myTerm -e $myMusic --next
hc keybind $Mod-Mod1-h spawn $myTerm -e $myMusic --previous
hc keybind $Mod-Mod1-j spawn $myTerm -e $myMusic --toggle-pause
hc keybind $Mod-Mod1-m spawn $myTerm -e $MMControl stop
hc keybind $Mod-Mod1-b spawn $myTerm -e $MMControl prev
hc keybind $Mod-Mod1-v spawn $myTerm -e $MMControl next
hc keybind $Mod-Mod1-x spawn $myTerm -e $MMControl toggle

# focusing clients
hc keybind $Mod-Left          focus left
hc keybind $Mod-Down          focus down
hc keybind $Mod-Up            focus up
hc keybind $Mod-Right         focus right
hc keybind $Mod-h             focus left
hc keybind $Mod-j             focus down
hc keybind $Mod-k             focus up
hc keybind $Mod-l             focus right

# minimize current window
herbstclient keybind $Mod-n spawn ~/.config/herbstluftwm/minimize.sh
# unminimize last window of a tag
herbstclient keybind $Mod-Shift-n mktemp string MINCLIENT mktemp int LASTIDATT chain \
  . set_attr LASTIDATT 0 \
  . foreach CLIENT clients. and \
    , sprintf MINATT "%c.minimized" CLIENT \
        compare MINATT "=" "true" \
    , sprintf TAGATT "%c.tag" CLIENT substitute FOCUS "tags.focus.name" \
        compare TAGATT "=" FOCUS \
    , sprintf CURRENTIDATT "%c.my_minimized_age" CLIENT and \
      : substitute LASTID LASTIDATT \
          compare CURRENTIDATT 'gt' LASTID \
      : substitute CURRENTID CURRENTIDATT \
          set_attr LASTIDATT CURRENTID \
    , set_attr MINCLIENT CLIENT \
  . and \
    , compare MINCLIENT "!=" "" \
    , substitute CLIENT MINCLIENT chain \
      : sprintf MINATT "%c.minimized" CLIENT \
          set_attr MINATT false \
      : sprintf CURRENTIDATT "%c.my_minimized_age" CLIENT \
          remove_attr CURRENTIDATT \


# moving clients
hc keybind $Mod-Shift-Left    shift left
hc keybind $Mod-Shift-Down    shift down
hc keybind $Mod-Shift-Up      shift up
hc keybind $Mod-Shift-Right   shift right
hc keybind $Mod-Shift-h       shift left
hc keybind $Mod-Shift-j       shift down
hc keybind $Mod-Shift-k       shift up
hc keybind $Mod-Shift-l       shift right

# splitting frames
hc keybind $Mod-u             split  bottom  0.5
hc keybind $Mod-o             split  right   0.5
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h      resize left +$resizestep
hc keybind $Mod-Control-j      resize down +$resizestep
hc keybind $Mod-Control-k      resize up +$resizestep
hc keybind $Mod-Control-l      resize right +$resizestep
hc keybind $Mod-Control-Left   resize left +$resizestep
hc keybind $Mod-Control-Down   resize down +$resizestep
hc keybind $Mod-Control-Up     resize up +$resizestep
hc keybind $Mod-Control-Right  resize right +$resizestep

# tags
tag_names=("" "" "" "" "" "")
tag_keys=( {1..6} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-m fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_padding 0
hc set focus_follows_mouse 1

hc attr theme.active.color '#222222'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color white
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#222222'
hc attr theme.active.outer_color '#222222'
hc attr theme.background_color '#141414'

hc set window_gap 3
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 1

# rules 
## Tag == workspace
hc unrule -F
hc rule class="google-chrome" tag=1 # move all browser to tag 1
hc rule class="LibreWolf" tag=1 # move browser to tag 1
hc rule class="mpv" tag=4 # move all browser to tag 1
hc rule class="atom" tag=3 # move all browser to tag 1
hc rule class="vlc" tag=3 # move all browser to tag 1
hc rule class="atom" tag=3 # move all browser to tag 1
hc rule class="stremio" tag=3 # move all browser to tag 1
hc rule class="gimp" tag=3 # move all browser to tag 1
hc rule class="VirtualBox" tag=5 # move all VMs to tag 5
hc rule title='Oracle VM VirtualBox Manager' tag=4
hc rule class="VirtualBox" pseudotile=on
hc rule class="VirtualBox" fullscreen=on
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
#hc hide_covered_windows true
# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1504x846+0+0
# or simply:
#hc detect_monitors
hc set_monitors 1920x1080+0+0 #1920x1060+1920+22 1920x1060+3840+22

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
