* Doom Emacs Configuration
** Other Things
Other things that aren't included here, should be documented in *config.org* make sure to read it.
** Requirements
*** Spelling
**** Requirements
1. Make sure to have *~/.doom.d/misc/english-words.txt*
2. Install the following packages: =aspell + aspell-en + hunspell + hunspell-en_us=
3. Install The following fonts =ttf-iosevka + ttf-cascadia-code + ttf-alegreya + ttf-ibm-plex + ttf-juliamono + ttf-jetbrains-mono=
**** To Change Spelling Language
Make sure to change the following to your preference.
(default) English-US
#+begin_src lisp
(setq ispell-dictionary "en_US")
(setq ispell-local-dictionary "en_US")
(setq ispell-local-dictionary-alist
      '(("en_US" "[[:alpha:]]" "[^[:alpha:]]" "[']" nil ("-d" "en_US") nil utf-8)))
(setq company-ispell-dictionary (concat doom-private-dir "misc/english-words.txt"))
#+end_src
**** Extra Info 
Some =Keybindings= To Make Your Life Easier, ~NOTE~ 'AC-STOP' can be used when /auto-complete/ interfere with /company-mode/ in ~prog-mode~

|-----+----------------------|
| Key | Function             |
|-----+----------------------|
| M-[ | Auto Completion      |
| M-] | Auto Completion Stop |
|-----+----------------------|
#NOTE Company-Mode (Ispell) Is Disabled In Favor Of Auto-Complete.
#NOTE To Enable Company-Mode Ispell Set The Following =company-ispell-available= to "t" In [[https://github.com/M1ndo/dotfiles/blob/master/.doom.d/config.org#ispell][Config.Org]]
**** Packages Installed
- mw-thesaurus "Thesaurus look up dictionary"
- auto-complete "Auto Complete Words"
- Flyspell+Grammar "Spell Check And Grammar Checking"
*** Latex + Org Export
**** Requirements
- For Latex Export and Latex Completion, Install The following packages
1. =texlive-bin= + =texlive-core=, =texlive-latexextra= (optional but install if you have problem compiling with my latex export template)
2. In order to use my custom latex templates make sure you have *~/.doom.d/Templates*

***** Using (Templates/Latex.Setup ..) 
#WARNING When Exporting Using One Of My Latex Templates (Templates/latex.setup ...) THERE ARE SOME ~REQUIREMENTS~.
Please Install Any Necessary Packages That Might Be Missing When Compiling .Tex file.
The fonts are currently in use when exporting are =Iosevka,Algreya SC,texgyreadventor,QTHeidelbergType,QTBlackForest= And [[https://brill.com/][Brill]]
To Install Any Latex Packages, Please Refer to [[https://wiki.archlinux.org/title/TeX_Live#tlmgr][Tlmgr]]
** To Know About
*** [[https://github.com/danielfm/smudge/][Smudge]] (Spotify Controller)
- Requires Spotify Premium To Control Spotify
- *READ THE CONFIGURATION PAGE ON THEIR REPO* And Change The Following API KEYS
- Doesn't require spotify premium to set song title in mode-line
- *INVOKE global-smudge-remote-mode and smudge-controller-toggle-play to set/update song in modeline*
#+begin_src lisp
(setq smudge-oauth2-client-secret "-----CLIENT-SECRET-----")
(setq smudge-oauth2-client-id "-----CLIENT-ID-----")
(setq smudge-player-status-format "%a - %t ◷ %l ")
(setq smudge-player-status-truncate-length 40)
(global-smudge-remote-mode)
#+end_src
*** Mpdmacs
- Control and display mpd status on mode-line
- Make sure to *change mpdmacs-host to yours in config.org*
#+begin_src lisp
(setq mpdmacs-host "127.0.0.1")
#+end_src
*** Mail In Emacs
For mail I'm using [[https://github.com/djcb/mu/][Mu (Mu4e)]] And [[https://isync.sourceforge.io/][Isync (Mbsync)]].
Configured specially for *gmail*, for other smtp server change it to your own
**** Requirements
1. Install the following packages: =Mu= (1.6.X Stable) + =Isync= + =msmtp= (Smtp Client To Send Mail)
**** Set Configs For Isync And Msmtp
- My configurations are available.
mbsync -> *~/.mbsync*
msmtp -> *~/.msmtprc*
***** Obtain Mail
In order for us to pull in all mail in our inbox, we need to create a folder called =Mail=
Then we can call mu and set our personal and secondary email addresses.
#+begin_src shell
mkdir ~/Mail
mu init --maildir ~/Mail/ --my-address=myemail@gmail.com --my-address=myemail2@gmail.com
#+end_src
**** Create "~/.doom.d/personal.el"
Add The following to it
#+begin_src lisp
;;;; -*- epa-file-encrypt-to: ("gpgmail@mai.com") -*-

(setq my_name "MY NAME")
(setq my_email "mymail@gmail.com")
(setq my_signature "Signed by me")
(setq my_hosts "mywebsite.com")

(setq my_name2 "MY NAME2")
(setq my_email2 "mymail2@gmail.com")
(setq my_signature2 "--- \nSigned by ME\nRANDOM QUOTE")
(setq my_hosts2 "mywebsite2.com")
#+end_src

** Custom Keybindings
This is just a small list of keybindings, please refer to the config file for more custom keybindings.

|--------------+----------------------------|
| Key          | Function                   |
|--------------+----------------------------|
| SPC-d-b      | Toggle Doom Modeline       |
| SPC-d-e      | Bufler Switch Buffer       |
| SPC-d-q      | Bufler Set Workspace Frame |
| SPC-d-w      | Consult Switch Buffer      |
| SPC-d-f      | Clippy Describe Function   |
| SPC-d-v      | Clippy Describe Variable   |
| SPC-d-t      | Chronos Timer Set          |
| SPC-d-p      | Org-Sidebar Tree Toggle    |
| SPC-d-l      | Org-SideBar Toggle         |
| SPC-d-z      | Window Zoom/Unzoom         |
|--------------+----------------------------|
| Spelling Key | Function                   |
|--------------+----------------------------|
| SPC-d-s-n    | Correct Next Word          |
| SPC-d-s-p    | Correct Previous Word      |
| SPC-d-s-r    | Spell Check On Region      |
|--------------+----------------------------|
| 0x0 Key      | Function                   |
|--------------+----------------------------|
| SPC-x-0      | Upload File To 0x0         |
| SPC-x-1      | Copy Buffer/Region To 0x0  |
|--------------+----------------------------|

* Installation
Make sure you have doom emacs installed and after that run.
#+begin_src shell
cp -r dotfiles/.doom.d/ ~/
# Make sure (You coppied the whole folder)
~/.emacs.d/bin/doom sync
# Wait for packages and for everything to install correctly.
#+end_src
* Emacs daemon
Look at systemd service if you want it instead (However its recommended)
Without systemd, add the following in ur autostart or run it manually..
#+begin_src shell
emacs --daemon
#+end_src
** Spawn emacs frame
*** Graphical
#+begin_src shell
emacsclient -c -a emacs
#+end_src
*** From tty
#+begin_src shell
emacsclient -c --tty
#+end_src
* Systemd Service
** Emacs Daemon
Create the following service in =~.config/systemd/user/emacs.service=
#+begin_src shell
[Unit]
Description=Emacs server daemon
Documentation=info:emacs man:emacs(1) https://gnu.org/software/emacs/

[Service]
Type=forking
ExecStart=sh -c 'emacs --daemon && emacsclient -c --eval "(delete-frame)"'
ExecStop=/usr/bin/emacsclient --no-wait --eval "(progn (setq kill-emacs-hook nil) (kill emacs))"
Restart=on-failure

[Install]
WantedBy=default.target
#+end_src
Then run
#+begin_src shell
systemctl --user enable emacs.service
systemctl --user start emacs.service
#+end_src
** Mbsync (Mu4e)
This is absolutely not necessary since, we have time in our =Emacs= Configuration that will sync our mail every 15minutes.
But if you're using some other email client that requires manual synchronization you can use this.
Create the following service in =~.config/systemd/user/mbsync.service=
#+begin_src shell
[Unit]
Description=mbsync service, sync all mail
Documentation=man:mbsync(1)
ConditionPathExists=%h/.mbsyncrc

[Service]
Type=oneshot
ExecStart=/usr/bin/mbsync -c %h/.mbsyncrc --all

[Install]
WantedBy=mail.target
#+end_src
Then create the following timer in =~.config/systemd/user/mbsync.timer=
#+begin_src shell
[Unit]
Description=call mbsync on all accounts every 5 minutes
ConditionPathExists=%h/.mbsyncrc

[Timer]
OnBootSec=5m
OnUnitInactiveSec=5m

[Install]
WantedBy=default.target
#+end_src
Finally run
#+begin_src shell
systemctl --user enable mbsync.timer
systemctl --user enable mbsync.service
systemctl --user start mbsync.service
#+end_src

#  LocalWords:  REPO mpdmacs config gmail smtp Configs
