#!/bin/bash
swayidle -w timeout 300 'swaylock' \
    timeout 600 'hyprctl dispatch dpms off' \
    resume 'hyprctl dispatch dpms on' \
    timeout 3600 'systemctl suspend' \
    before-sleep 'swaylock' &
