#!/usr/bin/env bash

###
# Adapted form here
# https://github.com/miroslavvidovic/rofi-scripts
###

declare -A URLS

URLS=(
  ["Brave Search"]="https://search.brave.com/search?q="
  ["Google"]="https://google.com/search?q="
  ["YouTube"]="https://www.youtube.com/results?search_query="
  ["GoPkg"]="https://pkg.go.dev/search?q="
  ["ArchA AUR"]="https://aur.archlinux.org/packages?O=0&K="
  ["Arch Wiki"]="https://wiki.archlinux.org/title/"
  ["Github"]="https://github.com/search?q="
  ["Urban"]="https://www.urbandictionary.com/define.php?term="
  ["The Sauraus"]="https://www.merriam-webster.com/thesaurus/"
  ["Wikipedia"]="https://en.wikipedia.org/wiki/Special:Search?go=Go&search="
  ["Google Images"]="https://images.google.fr/images?q="
  ["Imdb"]="https://www.imdb.com/find?s=all&q="
)

# List for rofi
gen_list() {
  for i in "${!URLS[@]}"
  do
    echo "$i"
  done
}

main() {
  # Pass the list to rofi
  platform=$( (gen_list) | dmenu -c -b -l 10 -fn 'VictorMono Nerd Font:size=10.5' -p "Search > " )

  if [[ -n "$platform" ]]; then
  query=$( (echo ) | dmenu -c -b -l 10 -fn 'VictorMono Nerd Font:size=10.5' -p "Query > " )

  if [[ -n "$query" ]]; then
  url=${URLS[$platform]}$query
  xdg-open "$url"
  else
    exit
  fi

  else
    exit
  fi
}

main

exit 0
